# name: Deploy

# on:
#   push:
#     branches: [main]

# env:
#   REGISTRY: ghcr.io

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read
#       packages: write

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: Setup Docker Buildx
#         uses: docker/setup-buildx-action@v3

#       - name: Log in to GitHub Container Registry
#         uses: docker/login-action@v3
#         with:
#           registry: ${{ env.REGISTRY }}
#           username: ${{ github.actor }}
#           password: ${{ secrets.GITHUB_TOKEN }}

#       # جادو: تبدیل نام ریپازیتوری به حروف کاملاً کوچک برای سازگاری با داکر
#       - name: Downcase repository name
#         run: |
#           echo "REPO_LOWER=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

#       - name: Build and push API server
#         uses: docker/build-push-action@v6
#         with:
#           context: .
#           file: infra/Dockerfile.api
#           push: true
#           cache-from: type=gha
#           cache-to: type=gha,mode=max
#           tags: |
#             ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}/api-server:latest
#             ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}/api-server:${{ github.sha }}

#       - name: Build and push Web app
#         uses: docker/build-push-action@v6
#         with:
#           context: .
#           file: infra/Dockerfile.web
#           push: true
#           cache-from: type=gha
#           cache-to: type=gha,mode=max
#           tags: |
#             ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}/web:latest
#             ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}/web:${{ github.sha }}

#       - name: Deploy to VPS
#         uses: appleboy/ssh-action@v1.2.0
#         env:
#           REPO_LOWER: ${{ env.REPO_LOWER }}
#           IMAGE_TAG: ${{ github.sha }}
#         with:
#           host: ${{ secrets.VPS_HOST }}
#           username: ${{ secrets.VPS_USER }}
#           password: ${{ secrets.VPS_PASSWORD }}
#           port : 9011
#           envs: REPO_LOWER,IMAGE_TAG
#           script: |
#             set -e
#             export GITHUB_REPOSITORY="${REPO_LOWER}"
#             export IMAGE_TAG="${IMAGE_TAG}"
#             cd ~/uni
#             bash scripts/deploy.sh

name: Test SSH Connection

on:
  push:
    branches: [main]

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Try SSH Connection to VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 9011
          script: |
            echo "========================================="
            echo "موفقیت‌آمیز بود! گیت‌هاب با موفقیت به سرور وصل شد."
            echo "مشخصات سرور:"
            uname -a
            echo "========================================="